---
title: "STRONG_Analysis"
author: "Brady Williamson"
date: "2024-04-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(performance)
library(datawizard)
library(openxlsx)
library(dplyr)
```

```{r functions}
scale_0_to_1 <- function(x) {
(x - min(x)) / (max(x) - min(x))
}
```

```{r prep_data}
lesion_load_df = read.csv()
m1_cc_df = read.csv()
demos_df = read.xlsx()
site_df = read.xlsx()
lesion_loc_df <- read.xlsx()
sex_df <- read.xlsx()
names(sex_df)[1] <- "Subject"
names(lesion_loc_df)[2] <- "LesionLocation"
colnames(demos_df)[1] <- colnames(lesion_load_df)[1]
colnames(site_df)[1] <- colnames(lesion_load_df)[1]
```

```{r}
# lesion_load_df$Lesion_Volume = log(lesion_load_df$Lesion_Volume + 1)
lesion_left <- ifelse(lesion_load_df$HCPA_Left > lesion_load_df$HCPA_Right, 1, 2)
lesion_load_df$Lesion.Side <- lesion_left
lesion_bilat = ifelse(lesion_load_df$HCPA_Left > 0 & lesion_load_df$HCPA_Right > 0, 1, 0)
lesion_load_df <- lesion_load_df[-which(lesion_bilat == 1),]
lesion_load_df$Total_Percsub_Cramer = lesion_load_df$Cramer_Left + lesion_load_df$Cramer_Right
lesion_load_df$Total_Percsub_HCP = lesion_load_df$HCP_Left + lesion_load_df$HCP_Right
lesion_load_df$Total_Percsub_HCPA = lesion_load_df$HCPA_Left + lesion_load_df$HCPA_Right
lesion_load_df$Total_Radial_Cramer = lesion_load_df$Radial_Cramer_Left + lesion_load_df$Radial_Cramer_Right
lesion_load_df$Total_Radial_HCP = lesion_load_df$Radial_HCP_Left + lesion_load_df$Radial_HCP_Right
lesion_load_df$Total_Radial_HCPA = lesion_load_df$Radial_HCPA_Left + lesion_load_df$Radial_HCPA_Right
lesion_load_df$Total_WLL_Cramer = lesion_load_df$WLL_Cramer_Left + lesion_load_df$WLL_Cramer_Right
lesion_load_df$Total_WLL_HCP = lesion_load_df$WLL_HCP_Left + lesion_load_df$WLL_HCP_Right
lesion_load_df$Total_WLL_HCPA = lesion_load_df$WLL_HCPA_Left + lesion_load_df$WLL_HCPA_Right
lesion_load_df$Total_Max_WLL_Cramer = lesion_load_df$Max_WLL_Cramer_Left + lesion_load_df$Max_WLL_Cramer_Right
lesion_load_df$Total_Max_WLL_HCP = lesion_load_df$Max_WLL_HCP_Left + lesion_load_df$Max_WLL_HCP_Right
lesion_load_df$Total_Max_WLL_HCPA = lesion_load_df$Max_WLL_HCPA_Left + lesion_load_df$Max_WLL_HCPA_Right
m1_cc_df$Total_M1 = m1_cc_df$Left_M1 + m1_cc_df$Right_M1
demos_and_ll_df = merge(demos_df, lesion_load_df, by="Subject")
subj_idxs <- which(m1_cc_df$Subject %in% demos_and_ll_df$Subject)
m1_cc_df <- m1_cc_df[subj_idxs,]
demos_and_ll_df = merge(demos_and_ll_df, m1_cc_df, by="Subject")
demos_and_ll_df = merge(demos_and_ll_df, site_df, by="Subject")
```

```{r}
demos_and_ll_df <- demos_and_ll_df[-which(demos_and_ll_df$StrokeSubtype_0Ischem_1ICH == 1),]

modeling_df <- demos_and_ll_df[-which(is.na(demos_and_ll_df$v2_FMtotal)),]
modeling_df <- modeling_df[-which(duplicated(modeling_df$Subject)),] 
modeling_df <- merge(modeling_df, lesion_loc_df, by="Subject")
modeling_df <- modeling_df %>% filter(LesionLocation == 1 | LesionLocation == 2)
modeling_df <- modeling_df[,c(1, 3:5, 6, 7, 32:52)]
low_n_sites <- names(which(table(modeling_df$Enrollment.Site) < 3))
modeling_df <- modeling_df[-which(modeling_df$Enrollment.Site %in% low_n_sites),]
modeling_df$Lesion.Side = as.factor(modeling_df$Lesion.Side)
modeling_df$Enrollment.Site = as.factor(modeling_df$Enrollment.Site)
```